### ISSUE TITLE
2.2.0 pre release for win not working properly due to "ln" issue in .py

### ISSUE THREAD

**Issue by PepeLopez** [TNTwise/REAL-Video-Enhancer#51] opened 2024-12-24 18:39 UTC
Before submitting an issue, please confirm it meets all the criteria
OS: Windows 10 AMD64
CPU: AMD Ryzen 9 7950X 16-Core Processor
GPU: AMD Radeon(TM) Graphics  6900 XT

**Describe the bug**
Any kind of upscaling not working, because error of "ln" (symlink) issue in a python file, see below in "logs"

**To Reproduce**
Try to encode something with AMD / ncnn

**Screenshots**

**Logs**
In commandline:
Done
Extracting File
Extracting: c:\CustomProgramme\REAL-Video-Enhancer-2.2.0pre\models\realesr-animevideov3-x2.tar.gz
The command “ln” is either misspelled or
could not be found.

In logfile:
rve-backend.py: error: unrecognized arguments: --video_encoder_preset libx264 --audio_encoder_preset aac --audio_bitrate 192k

 
**GPU**
Please state your GPU, and what you are using to render (pytorch, tensorrt, ncnn)

AMD 6900 XT, ncnn, any model

**Comment by TNTwise** [comment] 2024-12-24 19:02
Does 2.1.5 work?, 2.2.0 is a pre-release and unstable, not recommended for general usage.

**Comment by PepeLopez** [comment] 2024-12-24 20:14
Yes, 2.1.5 works pretty good on my system!
I know what a pre-release is 😄 
It's just meant as feedback for you. I know that not every developer can own every system component to test, it seems that my config or - at least ncnn? - is causing problems, I am just reporting this. I'm looking forward to the new version! Keep up the good work, I love it!

**Comment by TNTwise** [comment] 2024-12-24 20:16
Sorry, thanks for reporting. The issue is a mismatch between the front end and back end, as I made quite a few major changes to how encoding works. I will check to make sure that it is building correct. Again, sorry for the misunderstanding. 

Note: the "ln" symlink is a non issue, I don't know where in the program that exists (most likely in the os Python library), but it does not affect usage.

**Comment by TNTwise** [comment] 2024-12-26 17:13
Should be fixed

**Closed as completed** 2024-12-26 17:13 UTC
